#----------------------------------------------
# makefile for project
# SunicYosen
# 2020.05.28
#----------------------------------------------

BASE_DIR      = $(abspath .)
SRC_DIR       = $(BASE_DIR)/src
VCS_VERDI_DIR = $(BASE_DIR)/vcs-verdi
DC_DIR        = $(BASE_DIR)/dc

incude 